apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: local-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-gateway
  template:
    metadata:
      labels:
        app: local-gateway
    spec:
      containers:
        - name: app
          image: local/gateway:v1
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: local-gateway-svc
spec:
  type: NodePort
  selector:
    app: local-gateway
  ports:
    - name: local-gateway-port
      protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 31001
